version: '3.9'


services:
    django:
        build: ../backend/core
        container_name: bittensor-django
        expose:
          - 8000
        env_file:
          - ../backend/app_envs/django.env
          - ../backend/app_envs/postgres.env
        command: ["sh", "entrypoint.sh"]
        volumes:
          - static_source:/home/app/files/static_sources
          - static:/home/app/files/static
          - media:/home/app/files/media
          - logs:/home/app/files/logs
          - locale:/home/app/files/locale
        depends_on:
          - postgres
        user: app

    postgres:
      image: postgis/postgis:16-3.4-alpine
      container_name: bittensor-db
      ports:
        - "5432:5432"
      volumes:
        - postgres_bittensor:/var/lib/postgresql/data
      env_file:
        - ../backend/app_envs/postgres.env
      restart: always

    nginx:
      container_name: bittensor-nginx
      image: nginx:1.21-alpine
      ports:
        - "8080:80"
      depends_on:
        - django
      volumes:
        - ../nginx/conf/:/etc/nginx/conf.d/:ro
        - ../nginx/includes/:/etc/nginx/includes/:ro
        - media:/home/app/files/media
        - static:/home/app/files/static
        - static_source:/home/app/files/static_sources
      restart: always

volumes:
  postgres_bittensor:
  static:
  media:
  logs:
  locale:
  static_source: