version: '3.9'


services:
    django:
        build: ../backend/core
        container_name: bittensor-django-dev
        ports:
            - "${DJANGO_PORT}:8000"
        env_file:
          - ../backend/app_envs/django.env
          - ../backend/app_envs/postgres.env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - static_source:${BASEDIR}/files/static_sources
          - static:${BASEDIR}/files/static
          - media:${BASEDIR}/files/media
          - logs:${BASEDIR}/files/logs
        depends_on:
          - postgres
        user: app

    postgres:
      image: postgis/postgis:16-3.4-alpine
      container_name: bittensor-db-dev
      volumes:
        - postgres_bittensor:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      env_file:
        - ../backend/app_envs/postgres.env
      restart: always

    frontend:
        build: ../frontend
        container_name: bittensor-frontend-dev
        ports:
          - "${FRONTEND_PORT}:3000"
        volumes:
          - ./frontend:/app
        depends_on:
          - django
          - postgres
        restart: always
        command: ["npm", "run", "dev"]

volumes:
  postgres_bittensor:
  bittensor:
  static:
  static_source:
  media:
  logs: