name: linter
on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: CD to workdir
        run: cd backend/core

      - name: Install dependencies
        uses: CD to workdir
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with=linters --no-interaction --no-ansi

      - name: Black check
        uses: CD to workdir
        run: |
          black --check .

      - name : flake8 check
        uses: CD to workdir
        run: |
          flake8 --append-config .flake8