name: linter
on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          cd backend/core
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with=linters --no-interaction --no-ansi --no-root

      - name: Black check
        run: |
          cd backend/core
          black --check .

      - name : flake8 check
        run: |
          cd backend/core
          flake8 --append-config .flake8